<?php

namespace ReclamationBundle\Repository;

/**
 * RponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByThread($Requestid)
    {
        $query = "Select R.sujet, R.rep, R.rating from ReclamationBundle:Rponse R where R.requete = '$Requestid'";
        $q = $this->getEntityManager()->createQuery($query);
        return $q->getResult();

    }

}
