<?php

namespace ReclamationBundle\Repository;

/**
 * RponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RponseRepository extends \Doctrine\ORM\EntityRepository
{
}
