threads_index:
    path:     /
    defaults: { _controller: "CommunicationBundle:Threads:index" }
    methods:  GET

threads_show:
    path:     /{id}/show
    defaults: { _controller: "CommunicationBundle:Threads:show" }
    methods:  GET

threads_new:
    path:     /new
    defaults: { _controller: "CommunicationBundle:Threads:new" }
    methods:  [GET, POST]

threads_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommunicationBundle:Threads:edit" }
    methods:  [GET, POST]

threads_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommunicationBundle:Threads:delete" }
    methods:  DELETE
