dons_demande:
    resource: "@DonsBundle/Resources/config/routing/demande.yml"
    prefix:   /

dons_don:
    resource: "@DonsBundle/Resources/config/routing/don.yml"
    prefix:   /

don_homepage:
    path:     /donnation
    defaults: { _controller: DonsBundle:Default:index }

