refugee_hebergement:
    resource: "@RefugeeBundle/Resources/config/routing/hebergement.yml"
    prefix:   /hebergement

refugee_hebergementrequest:
    resource: "@RefugeeBundle/Resources/config/routing/hebergementrequest.yml"
    prefix:   /hebergementrequest


refugee_comment:
    resource: "@RefugeeBundle/Resources/config/routing/comment.yml"
    prefix:   /hebergement/comment

refugee_homepage:
    path:     /
    defaults: { _controller: RefugeeBundle:Default:index }
