<?php

namespace MissionBundle\Repository;

/**
 * MissionDonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionDonationRepository extends \Doctrine\ORM\EntityRepository
{
}
