<?php

namespace MissionBundle\Repository;

use MissionBundle\Entity\Mission;

/**
 * UpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByMission(Mission $mission)
    {
        return $this->createQueryBuilder('l')
            ->select('COUNT(l) AS likes')
            ->andWhere('l.mission = :mission')
            ->setParameter('mission', $mission->getId())
            ->getQuery()
            ->getSingleScalarResult();

    }
}
