<?php

namespace AssociationBundle\Repository;

/**
 * AdheranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdheranceRepository extends \Doctrine\ORM\EntityRepository
{
}
