<?php

namespace AssociationBundle\Repository;

use AppBundle\Entity\User;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAssociationAdmin(User $user)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.admin = :val')
            ->setParameter('val', $user)
            ->getFirstResult()
            ;
    }
}
