<?php

namespace AssociationBundle\Repository;

/**
 * GouverneratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GouverneratRepository extends \Doctrine\ORM\EntityRepository
{
}
