# Front : Tjiblou reclamationet l connecté : to get current user $this->getUser()
requete_index:
    path:     /
    defaults: { _controller: "ReclamationBundle:Requete:index" }
    methods:  GET

add_requete:
    path:     /add
    defaults: { _controller: "ReclamationBundle:Requete:add" }
    methods:  POST

requete_show:
    path:     /{id}/show
    defaults: { _controller: "ReclamationBundle:Requete:show" }
    methods:  GET
# Front
requete_new:
    path:     /new
    defaults: { _controller: "ReclamationBundle:Requete:new" }
    methods:  [GET, POST]
# Front : Bonus points, can only update if status = PENDING
requete_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReclamationBundle:Requete:edit" }
    methods:  [GET, POST]
# Front
requete_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReclamationBundle:Requete:delete" }
    methods:  DELETE

add_requete_API:
    path:     /api/add
    defaults: { _controller: "ReclamationBundle:Requete:addApi" }
    methods:  POST

update_requete_API:
    path:     /{id}/api/edit
    defaults: { _controller: "ReclamationBundle:Requete:editApi" }
    methods:  POST

show_requete_API:
    path:     /api/showall
    defaults: { _controller: "ReclamationBundle:Requete:getall" }
    methods:  GET


delete_requete_API:
    path:     /{id}/api/delete
    defaults: { _controller: "ReclamationBundle:Requete:deleteApi" }
    methods:  POST

show_id_rponse_API:
    path:     /api/{id}/show
    defaults: { _controller: "ReclamationBundle:Requete:showApi" }
    methods:  GET

