<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAdmin(User $user)
    {
        return $this->createQueryBuilder('genus')
            ->andWhere('genus.admin = :admin')
            ->setParameter('admin', $user->getId())
            ->getQuery()
            ->execute();
    }
}
