association_association:
    resource: "@AssociationBundle/Controller/AssociationController.php"
    type:     annotation

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /

refugee:
    resource: "@RefugeeBundle/Resources/config/routing.yml"
    prefix:   refugee/

communication:
    resource: "@CommunicationBundle/Resources/config/routing.yml"
    prefix:   /

dons:
    resource: "@DonsBundle/Resources/config/routing.yml"
    prefix:   /

mission:
    resource: "@MissionBundle/Resources/config/routing.yml"
    prefix:   /

association:
    resource: "@AssociationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"