<<<<<<< HEAD
association_category:
=======
Xassociation_category:
>>>>>>> c1d7068c8cb78f7dde51e42f29e72543307a0037
    resource: "@AssociationBundle/Controller/CategoryController.php"
    type:     annotation

association_association:
    resource: "@AssociationBundle/Controller/AssociationController.php"
    type:     annotation

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

refugee:
    resource: "@RefugeeBundle/Resources/config/routing.yml"
    prefix:   /refugees

communication:
    resource: "@CommunicationBundle/Resources/config/routing.yml"
    prefix:   /Forum

dons:
    resource: "@DonsBundle/Resources/config/routing.yml"
    prefix:   /dons

mission:
    resource: "@MissionBundle/Controller/"
    type:     annotation
    prefix:   /


association:
    resource: "@AssociationBundle/Controller/"
    type:     annotation
    prefix:   /

backoffice:
    resource: "@BackofficeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /front

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_association_register:
    path:     /register/admin/association
    defaults: { _controller: AppBundle:Registration:registerAdminAssociation }
