# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    AssociationBundle\DataFixtures\:
        resource: '../../src/AssociationBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_client_registration }