<?php

namespace CommunicationBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByThread($threadId){
        $query = "Select C.id, C.date, C.content from CommunicationBundle:Comments C where C.thread = '$threadId'";
        $q = $this->getEntityManager()->createQuery($query);
        return $q->getResult();
    }
}
