<?php

namespace CommunicationBundle\Repository;

/**
 * ForumCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
