<?php

namespace CommunicationBundle\Repository;

/**
 * ThreadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadsRepository extends \Doctrine\ORM\EntityRepository
{
}
