<?php

namespace DonsBundle\Repository;

use DonsBundle\Entity\Don;
use DonsBundle\Entity\PostLike;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLikeRepository extends \Doctrine\ORM\EntityRepository
{

    public function countByDon(Don $don)
    {
        return $this->createQueryBuilder('l')
            ->select('COUNT(l) AS likes')
            ->andWhere('l.don = :don')
            ->setParameter('don', $don)
            ->getQuery()
            ->getSingleScalarResult();

    }

    }




