<?php

namespace RefugeeBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function nbrCommentsByHebergement($hebergementId)
    {
        $query = $this->createQueryBuilder('c')
            ->select('count(c.id)')
            ->where('c.hebergement = ' . ':hebergementId')
            ->setParameters(
                [
                    'hebergementId' => $hebergementId
                ]
            )
            ->getQuery();

        return $query->getResult()[0]['1'];
    }

    public function findOrdreByDate($hebergementId)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.hebergement = ' . ':hebergementId')
            ->orderBy('c.id', 'DESC')
            ->setParameters(
                [
                    'hebergementId' => $hebergementId
                ]
            )
            ->getQuery();

        return $query->getResult();
    }
}
