<?php

namespace RefugeeBundle\Repository;

/**
 * HebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($governorat, $nbrRooms, $duration)
    {
        $query = $this->createQueryBuilder('h')
            ->where('h.governorat = ' . ':governorat')
            ->orWhere('h.nbrRooms = ' . ':nbrRooms')
            ->orWhere('h.duration = ' . ':duration')
            ->setParameters(
                [
                    'governorat' => $governorat,
                    'nbrRooms' => $nbrRooms,
                    'duration' => $duration
                ]
            )
            ->getQuery();

        return $query->getResult();
    }
}
