<?php

namespace RefugeeBundle\Repository;

/**
 * HebergementRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
