<?php

namespace RefugeeBundle\Repository;

/**
 * RefugeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugeeRepository extends \Doctrine\ORM\EntityRepository
{
}
