demande_index:
    path:     /
    defaults: { _controller: "DonsBundle:Demande:index" }
    methods:  GET

demande_show:
    path:     /{id}/show
    defaults: { _controller: "DonsBundle:Demande:show" }
    methods:  GET

demande_new:
    path:     /new
    defaults: { _controller: "DonsBundle:Demande:new" }
    methods:  [GET, POST]

demande_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonsBundle:Demande:edit" }
    methods:  [GET, POST]

demande_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonsBundle:Demande:delete" }
    methods:  DELETE
demande_search:
    path:     /search
    defaults: { _controller: "DonsBundle:Demande:search" }
    methods: GET

demandeApi:
    path:     /api
    defaults: { _controller: "DonsBundle:Api:demandeApi"}


demande_addApi:
    path:     /addapi
    defaults: { _controller: "DonsBundle:Api:addDemande"}
    methods:  [GET, POST]

apidemande_show:
    path:     /apishow
    defaults: { _controller: "DonsBundle:Api:demandeShow" }
    methods:  GET

apidemande_delete:
    path:     /remove
    defaults: { _controller: "DonsBundle:Api:removeDemande" }
    methods:  GET