demande_index:
    path:     /demandes
    defaults: { _controller: "DonsBundle:Demande:index" }
    methods:  GET

demande_show:
    path:     /{id}/front/show
    defaults: { _controller: "DonsBundle:Demande:show" }
    methods:  GET

demande_new:
    path:     front/new
    defaults: { _controller: "DonsBundle:Demande:new" }
    methods:  [GET, POST]

demande_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonsBundle:Demande:edit" }
    methods:  [GET, POST]

demande_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonsBundle:Demande:delete" }
    methods:  DELETE
demande_search:
    path:     front/search
    defaults: { _controller: "DonsBundle:Demande:search" }
    methods: GET

demande_back:
    path:     /dashboard/admin/demandes
    defaults: { _controller: "DonsBundle:DemandeBack:index" }
    methods:  GET


demande_back_new:
    path:     /dashboard/admin/demandes/new
    defaults: { _controller: "DonsBundle:DemandeBack:new" }
    methods:  GET
demande_back_show:
    path:     /dashboard/admin/demandes/{id}/show
    defaults: { _controller: "DonsBundle:DemandeBack:show" }
    methods:  GET

demande_like:
    path:     /fornt/{id}/like
    defaults: { _controller: "DonsBundle:Demande:like" }