don_index:
    path:     /
    defaults: { _controller: "DonsBundle:Don:index" }
    methods:  GET

don_show:
    path:     /{id}/show
    defaults: { _controller: "DonsBundle:Don:show" }
    methods:  GET

don_new:
    path:     /new
    defaults: { _controller: "DonsBundle:Don:new" }
    methods:  [GET, POST]

don_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonsBundle:Don:edit" }
    methods:  [GET, POST]

don_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonsBundle:Don:delete" }
    methods:  DELETE
don_home:
    path:     /home
    defaults: { _controller: "DonsBundle:Don:home" }
don_search:
    path:     /search
    defaults: { _controller: "DonsBundle:Don:search" }
    methods: GET
don_like:
    path:     /{id}/like
    defaults: { _controller: "DonsBundle:Don:like" }

don_api:
    path:     /api
    defaults: { _controller: "DonsBundle:Api:don"}

don_addApi:
    path:     /addapi
    defaults: { _controller: "DonsBundle:Api:add"}
    methods:  [GET, POST]

apidon_show:
    path:     /apishow
    defaults: { _controller: "DonsBundle:Api:apishow" }
    methods:  GET

apidon_delete:
    path:     /remove
    defaults: { _controller: "DonsBundle:Api:remove" }
    methods:  GET
apidon_update:
    path:     /apiedit
    defaults: { _controller: "DonsBundle:Api:apiedit" }
    methods:  [GET, POST]
