imagedon_index:
    path:     /
    defaults: { _controller: "DonsBundle:ImageDon:index" }
    methods:  GET

imagedon_show:
    path:     /{id}/show
    defaults: { _controller: "DonsBundle:ImageDon:show" }
    methods:  GET

imagedon_new:
    path:     /new
    defaults: { _controller: "DonsBundle:ImageDon:new" }
    methods:  [GET, POST]

imagedon_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonsBundle:ImageDon:edit" }
    methods:  [GET, POST]

imagedon_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonsBundle:ImageDon:delete" }
    methods:  DELETE
