communication_forumcategory:
    resource: "@CommunicationBundle/Resources/config/routing/forumcategory.yml"
    prefix:   /forumcategory

communication_threads:
    resource: "@CommunicationBundle/Resources/config/routing/threads.yml"
    prefix:   /threads

communication_comments:
    resource: "@CommunicationBundle/Resources/config/routing/comments.yml"
    prefix:   /comments

communication_homepage:
    path:     /
    defaults: { _controller: CommunicationBundle:Default:index }
forum_homepage:
    path:     /home
    defaults: { _controller: CommunicationBundle:ForumCategory:home }
thread_homepage:
    path:     /thread
    defaults: { _controller: CommunicationBundle:Threads:home }
thread_add:
    path:     /thread/add
    defaults: { _controller: CommunicationBundle:Threads:add }
thread_comments:
    path:     /thread/comment
    defaults: { _controller: CommunicationBundle:Threads:show }
thread_recherche:
    path:     /recherche
    defaults: { _controller: CommunicationBundle:Threads:recherche }






