comment_index:
    path:     /
    defaults: { _controller: "RefugeeBundle:Comment:index" }
    methods:  GET

comment_show:
    path:     /{id}/show
    defaults: { _controller: "RefugeeBundle:Comment:show" }
    methods:  GET

comment_new:
    path:     /new
    defaults: { _controller: "RefugeeBundle:Comment:new" }
    methods:  [GET, POST]

comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "RefugeeBundle:Comment:edit" }
    methods:  [GET, POST]

comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "RefugeeBundle:Comment:delete" }
    methods:  DELETE
