hebergement_index:
    path:     /
    defaults: { _controller: "RefugeeBundle:Hebergement:index" }
    methods:  [GET, POST]

hebergement_search:
    path:     /search
    defaults: { _controller: "RefugeeBundle:Hebergement:search" }
    methods:  [GET]

hebergement_show:
    path:     /{id}/show
    defaults: { _controller: "RefugeeBundle:Hebergement:show" }
    methods:  GET

hebergement_new:
    path:     /new
    defaults: { _controller: "RefugeeBundle:Hebergement:new" }
    methods:  [GET, POST]

hebergement_edit:
    path:     /{id}/edit
    defaults: { _controller: "RefugeeBundle:Hebergement:edit" }
    methods:  [GET, POST]

hebergement_delete:
    path:     /{id}/delete
    defaults: { _controller: "RefugeeBundle:Hebergement:delete" }
    methods:  DELETE
