refugee_image_index:
    path:     /
    defaults: { _controller: "RefugeeBundle:Image:index" }
    methods:  GET

refugee_image_show:
    path:     /{id}/show
    defaults: { _controller: "RefugeeBundle:Image:show" }
    methods:  GET

refugee_image_new:
    path:     /new
    defaults: { _controller: "RefugeeBundle:Image:new" }
    methods:  [GET, POST]

refugee_image_edit:
    path:     /{id}/edit
    defaults: { _controller: "RefugeeBundle:Image:edit" }
    methods:  [GET, POST]

refugee_image_delete:
    path:     /{id}/delete
    defaults: { _controller: "RefugeeBundle:Image:delete" }
    methods:  DELETE
